import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Astra HCIS",
  manifest: "/manifest.json",
  description: "Generated by create next app",
  icons: [{ rel: "shortcut icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="theme-color" content="#317EFB" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="HCIS PWA" />
      </Head>
      <body className={`md:w-[480px] w-full mx-auto ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
